spring.config.activate.on-profile=supabase

spring.datasource.url=${SUPABASE_DB_URL:jdbc:postgresql://db.admtwxejbgacvvhje.supabase.co:5432/postgres?sslmode=require}
spring.datasource.username=${SUPABASE_DB_USER:postgres}
spring.datasource.password=${SUPABASE_DB_PASSWORD:Simbran-2005}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.data-source-properties.sslmode=require
